/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as DevRouteImport } from "./routes/dev";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DevSyncRouteImport } from "./routes/dev.sync";
import { Route as DevMutationsRouteImport } from "./routes/dev.mutations";
import { Route as CoursesCourseIdRouteImport } from "./routes/courses.$courseId";

const DevRoute = DevRouteImport.update({
  id: "/dev",
  path: "/dev",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DevSyncRoute = DevSyncRouteImport.update({
  id: "/sync",
  path: "/sync",
  getParentRoute: () => DevRoute,
} as any);
const DevMutationsRoute = DevMutationsRouteImport.update({
  id: "/mutations",
  path: "/mutations",
  getParentRoute: () => DevRoute,
} as any);
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: "/courses/$courseId",
  path: "/courses/$courseId",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dev": typeof DevRouteWithChildren;
  "/courses/$courseId": typeof CoursesCourseIdRoute;
  "/dev/mutations": typeof DevMutationsRoute;
  "/dev/sync": typeof DevSyncRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dev": typeof DevRouteWithChildren;
  "/courses/$courseId": typeof CoursesCourseIdRoute;
  "/dev/mutations": typeof DevMutationsRoute;
  "/dev/sync": typeof DevSyncRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dev": typeof DevRouteWithChildren;
  "/courses/$courseId": typeof CoursesCourseIdRoute;
  "/dev/mutations": typeof DevMutationsRoute;
  "/dev/sync": typeof DevSyncRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dev"
    | "/courses/$courseId"
    | "/dev/mutations"
    | "/dev/sync";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/dev" | "/courses/$courseId" | "/dev/mutations" | "/dev/sync";
  id:
    | "__root__"
    | "/"
    | "/dev"
    | "/courses/$courseId"
    | "/dev/mutations"
    | "/dev/sync";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DevRoute: typeof DevRouteWithChildren;
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/dev": {
      id: "/dev";
      path: "/dev";
      fullPath: "/dev";
      preLoaderRoute: typeof DevRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dev/sync": {
      id: "/dev/sync";
      path: "/sync";
      fullPath: "/dev/sync";
      preLoaderRoute: typeof DevSyncRouteImport;
      parentRoute: typeof DevRoute;
    };
    "/dev/mutations": {
      id: "/dev/mutations";
      path: "/mutations";
      fullPath: "/dev/mutations";
      preLoaderRoute: typeof DevMutationsRouteImport;
      parentRoute: typeof DevRoute;
    };
    "/courses/$courseId": {
      id: "/courses/$courseId";
      path: "/courses/$courseId";
      fullPath: "/courses/$courseId";
      preLoaderRoute: typeof CoursesCourseIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface DevRouteChildren {
  DevMutationsRoute: typeof DevMutationsRoute;
  DevSyncRoute: typeof DevSyncRoute;
}

const DevRouteChildren: DevRouteChildren = {
  DevMutationsRoute: DevMutationsRoute,
  DevSyncRoute: DevSyncRoute,
};

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevRoute: DevRouteWithChildren,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
